version: "3"
services:
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

  ejs:
    restart: unless-stopped
    build: /src/app/
    image: ejs-challenge:latest
    ports:
      - 9090:3000

volumes:
  mongo-data:
