version: "3"
services:
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

  ejs:
    restart: unless-stopped
    #build: /src/app/
    image: danidlx/ejs-challenge-imageBR

    ports:
      - 9090:3000
    environment: 
      DB_NAME: meubanco
      DB_PORT: 27017
      DB_HOST: mongo

volumes:
  mongo-data:
