apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "ejs-challenge.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.envMap }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
