version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.13.0



jobs:
  build-and-push:
    executor: gcp-gcr/default
    # docker:
    #   - image: circleci/node:stretch
        # environment:
        #   DATABASE_NAME: ejs_bas
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
        google-compute-zone: us-east1-b
        google-project-id: ead-ucam
        image: ejs-circleci-image
      - run:
        name: Building 
        command: | 
          docker build . -t gcr.io/ead-ucam/ejs-circleci-image:0.1.0
          docker push gcr.io/ead-ucam/ejs-circleci-image:0.1.0