apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejs-deployment
  labels:
    app: ejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ejs
  template:
    metadata:
      labels:
        app: ejs
    spec:
      containers:
      - name: ejs-challenge-app
        image: gcr.io/ead-ucam/ejs-challenge:1.1
        ports:
        - containerPort: 3000
        envFrom: 
        - configMapRef:
            name: configmap-ejs
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 500Mi
---

apiVersion: v1
kind: Service
metadata:
  name: ejs-service
spec:
  selector:
    app: ejs
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
