apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-ejs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ejs-deployment
  minReplicas: 2
  maxReplicas: 7
  targetCPUUtilizationPercentage: 50
